git clone https://github.com/kchmck/vim-coffee-script.git	 .vim/bundle/vim-coffee-script
git clone https://github.com/digitaltoad/vim-jade.git .vim/bundle/vim-jade
git clone https://github.com/wavded/vim-stylus.git .vim/bundle/vim-stylus
git clone https://github.com/scrooloose/syntastic.git	 .vim/bundle/syntastic
git clone https://github.com/tpope/vim-sensible.git	 .vim/bundle/vim-sensible
git clone https://github.com/tpope/vim-rails.git	 .vim/bundle/vim-rails
git clone https://github.com/mileszs/ack.vim.git	 .vim/bundle/ack.vim
git clone https://github.com/tpope/vim-fugitive.git	 .vim/bundle/vim-fugitive
git clone https://github.com/jgdavey/tslime.vim.git	 .vim/bundle/tslime.vim
git clone https://github.com/tpope/vim-dispatch.git	 .vim/bundle/vim-dispatch
git clone https://github.com/felixge/vim-nodejs-errorformat.git	 .vim/bundle/vim-nodejs-errorformat
git clone https://github.com/nosami/Omnisharp.git	 .vim/bundle/Omnisharp
git clone https://github.com/briancollins/vim-jst.git	 .vim/bundle/vim-jst
git clone https://github.com/pangloss/vim-javascript.git	 .vim/bundle/vim-javascript
git clone git@github.com:tpope/vim-surround.git	 .vim/bundle/vim-surround
git clone git@github.com:guns/vim-clojure-static.git   .vim/bundle/vim-clojure-static
git clone https://github.com/tpope/vim-fireplace.git	 .vim/bundle/vim-fireplace
git clone https://github.com/vim-scripts/paredit.vim.git	 .vim/bundle/paredit.vim.git
git clone https://github.com/kien/ctrlp.vim.git	 .vim/bundle/ctrlp.vim
git clone https://github.com/dgrnbrg/vim-redl.git .vim/bundle/vim-redl
git clone git@github.com:jimenezrick/vimerl.git .vim/bundle/vimerl
git clone https://github.com/scrooloose/nerdtree.git .vim/bundle/nerdtree
git clone git://github.com/altercation/vim-colors-solarized.git .vim/bundle/vim-solarized
git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline
git clone git@github.com:mxw/vim-jsx.git ~/.vim/bundle/vim-jsx
git clone https://github.com/edkolev/erlang-motions.vim ~/.vim/bundle/erlang-motions.vim
git clone git@github.com:eagletmt/ghcmod-vim.git ~/.vim/bundle/ghcmod-vim
git clone git@github.com:eagletmt/neco-ghc.git ~/.vim/bundle/neco-ghc
git clone https://github.com/raichoo/haskell-vim.git ~/.vim/bundle/haskell-vim
