#!/bin/bash
cd ~/environments/id3as/src/osk

gnome-terminal --working-directory=~/environments/id3as --command "bash run.sh /osk.sh"
gnome-terminal --working-directory=~/environments/id3as/src/osk --command "vim"

super chown -R $USER .
super chgrp -R $USER .
exit
