pacman -S dialog
pacman -S mesa
pacman -S --needed base-devel
pacman -S iw
pacman -S wpa_supplicant
pacman -S wpa_actiond
pacman -S vim
pacman -S git
pacman -S xmonad
pacman -S xmonad-contrib
pacman -S gnome-flashback
pacman -S gnome-extra
pacman -S gdm
pacman -S xmodmap
pacman -S xorg-xinit
pacman -S xterm
pacman -S dmenu
pacman -S acpi
pacman -S htop
pacman -S xscreensaver
pacman -S libxss
pacman -S terminator
pacman -S acpilight
pacman -S cpupower
pacman -S lightdm lightdm-gtk-greeter
systemctl enable lightdm.service
pacman -S docker
pacman -S xcompmgr
pacman -S tmux
pacman -S vlc
pacman -S qt4
pacman -S erlang
pacman -S nodejs
pacman -S wireshark-qt
sudo npm install -g elm-format
pacman -S pcre 
pacman -S pkg-config 
pacman -S automake
pacman -S units
pacman -S msitools
